AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS API Gateway using the REST Protocol. We use AWS Lambda for serveless computing and DynamoDB for the database.

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  getAllPatientsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-patients.getAllPatientsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP get method to get all patients from the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PatientsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /patients
            Method: GET
  postPatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/post-patient.postPatientHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP post method to add one patient to the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Environment:
        Variables:
          TABLE_NAME: !Ref PatientsTable
          BUCKET_NAME: !Ref ImagesBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /patients
            Method: POST
  deletePatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-patient.deletePatientHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP delete method to delete one patient by id from the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Environment:
        Variables:
          TABLE_NAME: !Ref PatientsTable
          BUCKET_NAME: !Ref ImagesBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /patients/{id}
            Method: DELETE
  optionsPatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/options-patient.optionsPatientHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP delete method to delete one patient by id from the DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /patients/{id}
            Method: OPTIONS
  getPaginatedPatientsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-paginated-patients.getPaginatedPatientsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP delete method to delete one patient by id from the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PatientsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /patients/{id}/{limit}
            Method: GET
  PatientsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: images-bucket-profile-pictures

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
