version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "back-end"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xcfdtlnfojcx"
s3_prefix = "back-end"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = false
